baseurl = "/"
languageCode = "en"
publishdir = "public"
canonifyUrls = true
paginate = 5
enableEmoji = true
theme = "hugo-landing-page"
title = "Photoveda -  Image editor" 
[markup.goldmark.renderer]
    unsafe = true
    block = true
    title = true

[author]
    name = "Girish Venkatachalam"
    email = "girish@photoveda.pro"
[params]
    description = "Photoveda - Image editor [API, browser tool and Chrome plugin]" 
    images =  ["images/screenshots/headshot.jpg"]
    title =  "Photoveda - edit your images"
    contactLink = "contact"
    copyright = "© {year} <a href=\"https://www.photoveda.pro/\" target=\"_blank\">Photoveda</a>"
    logo = "images/photoveda-logo.png"
    footerlogo = "images/photoveda-logo.png"
    footerDescription = "Edit your images using the browser"

[[params.headermenu]]
   link = "/api"
   title = "API"
[[params.headermenu]]
   link = "/join-waitlist"
   title = "Join waitlist"
[[params.headermenu]]
   link = "/blog"
   title = "Blog"
[[params.headermenu]]
  link = "/pricing"
  title = "Pricing"
[[params.headermenu]]
  link = "/comparison"
  title = "Compare us"
[[params.headermenu]]
  link = "/faq"
  title = "FAQ"


[[params.social]]
    title = "Twitter"
    url = "https://twitter.com/girish1729" 
